os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER=g++-8
        - CC=gcc-8
        - CXX=g++-8
install:
  - pip install conan
  - conan user
script:
  - mkdir build && cd build
  - conan install .. -scompiler.version=8 -scompiler.libcxx=libstdc++11
  - cmake .. -G "Unix Makefiles"
  - cmake --build .
  - CTEST_OUTPUT_ON_FAILURE=1 ctest
